### ISSUE TITLE
Index Controller Binding Problems

### ISSUE THREAD

**Issue by InsaneGrox** [boyestrous/elite-vr-cockpit#15]
1: Pov 3 bindings are broken in the ship for me, I'd assume they'd be my throttle stick or touchpad, however neither one do anything, this includes clicking too so lateral thrust and boosting are impossible with the default bindings
2: Any menu that doesn't use the virtual HOTAS is broken, system/galaxy views don't function, the text showing how to use them is cut off, and the FSS is unusable outside of the calibration button.

**Comment by boyestrous** [comment]
Thanks for letting me know!

Can you confirm that you're using the [Valve Index controllers like these](https://www.amazon.com/Valve-Index-Controllers-PC-Mac/dp/B086DJXXKV)?

**Please send me the following files (copy/paste or attach) so I can diagnose:**
1. Please attach your bindings file, which is named "Custom.4.0.binds" and located at: _C:\Users\YOURNAME\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings_

2. The player log file, which is located at:
_C:\Users\YOURNAME\AppData\LocalLow\Boyestrous\Elite VR Cockpit\Player.log_

For the galaxy map instructions, I have a new release almost ready to publish, I'll try to get it uploaded today. Version 0.9.3 fixes the instruction texts.

**Comment by InsaneGrox** [comment]
1: I got my index controllers directly from valve, not amazon, but they should be identical.
2: github doesn't like .binds files soooo
[stuff.zip](https://github.com/boyestrous/elite-vr-cockpit/files/12383717/stuff.zip)

**Comment by boyestrous** [comment]
Got it!

I'll take a look and see if I can figure it out asap. You're right that the controllers should be identical.

for line 90: yeah, it's not a fan of that, but so far it hasn't caused a problem for the few dozen times I've done it :)

**Comment by boyestrous** [comment]
### Ok, try this:

1. copy all contents from this [updated bindings file](https://github.com/boyestrous/elite-vr-cockpit/blob/main/Assets/StreamingAssets/SteamVR/bindings_knuckles.json)

2. Find the folder where you unzipped the latest release (probably your downloads folder?) and navigate to the following sub-folder
Downloads > EliteVRCockpit-v0.9.2 > Elite VR Cockpit_Data > StreamingAssets > SteamVR

3. Find the file named **bindings_knuckles.json** and replace all of the content with what you copied above. 

## More details
I think the problem is that the bindings file from the last release didn't have a control bound to the POV3 control, which is set up to be on the throttle side. The bindings_knuckles.json file is what tells SteamVR which physical button aligns to which virtual control. The file that was included in the last release only had POV1 and POV2, so it makes sense that your POV3 wasn't working!

I also fixed some connections to the FSS mode controls, Map Controls, and Menu Mode, so hopefully, this will take care of all of the problems. 

If you find something doesn't work, you can edit the bindings yourself through the SteamVR Bindings UI. Just please let me know what you end up changing, so I can include those changes in future releases? If you can't tell, I don't have the Index controllers, so I'm making educated guesses here...

I'm planning to roll out a new release with a few other fixes this weekend. So if this works, I'll roll in this change as well.

**Comment by InsaneGrox** [comment]
Yep, that fixed it

**Comment by boyestrous** [comment]
Updated bindings are included in Release 0.9.3, which was just uploaded
