### ISSUE TITLE
Using a large amount of CPU and GPU

### ISSUE THREAD

**Issue by geekbozu** [boyestrous/elite-vr-cockpit#29]
Wondering if I could get some insights as to why so much resource which causes ED and everything to lag pretty bad. 
![image](https://github.com/boyestrous/elite-vr-cockpit/assets/4099721/0da2d06c-787d-4908-9663-1ba49b2859bb)

PC Specs
AMD 7840u 
3060 12GB eGPU
64gb Ram

Software is all forced to run on eGPU. I have confirmed that in nvidia-smi
Its using a substantial amount of resources to render for somereason. Am very confused.

**Comment by boyestrous** [comment]
Sorry to hear that! I know the overlay tends to be CPU intensive (on top of the game) itself. Do you, by chance, have an idea of the baseline for the game running in VR (without the EVRC mod)?

In the meantime, I had to drop my settings a bit to get a smooth VR experience in the beginning. I've made some performance improvements, but it's still not excellent... There are some visual settings that you can tweak. I followed this guide because he does a good job of explaining the highest "bang for buck" on each of the settings: https://www.youtube.com/watch?v=G7efYzpquIs&t=789s&pp=ygUhZWxpdGUgZGFuZ2Vyb3VzIGdyYXBoaWNzIHNldHRpbmdz

If you can get me some details on the baseline CPU/GPU utilization, I might be able to help you figure out what's happening. Let me know!

**Comment by geekbozu** [comment]
I can try to get anything that will help!

In this case before launching the overlay I was getting about 6ms frame times. I will have to validate CPU usage. 
In VR without EVRC it self is smooth with minimal frame drops. 
I should call out I'm using a quest 3, so there is some hardware enc overhead but I don't think that's correlated here. 
With the overlay It was eating up half my 3060 (see the screenshot) and due to that ED was getting a very choppy inconsistent frame rate.
I should also call out the eGPU is kind of weird in that its bandwidth limited so if your reloading textures often that could be an issue/bottle neck thats exasperated with this setup.  Its more or less a 3060 in a pcie-x1 slot instead of an x8 or x16 :)

**Comment by boyestrous** [comment]
Yeah, the 1X GPU thing is definitely part of the issue. I've been optimizing for a few months now by trying to remove extra renders from the unity engine. 

This has helped, but each Holographic button needs to be re-rendered every so often to keep them visible in VR. There's only so much I can do about that. 

**Here are a couple other tips that might help:**
- If you have chrome open (it's hard to avoid with Elite Dangerous), disable hardware acceleration and close all unnecessary tabs 
- I have used a laptop for Inara or other sites instead of my gaming PC, but it does stink to not be able to copy/paste
- make the Elite Dangerous game window low resolution on your desktop monitor (like 640x480)
- do not use the SteamVR view window (the little screen that mirrors what you see in VR)
- depending on your headset, make sure you're hardwired to the computer instead of using wireless (even using Ethernet cables to connect just the computer to the network can make a big difference)
- turn off any secondary displays outside of VR. In your case, only have the laptop monitor on and maybe consider lowering the overall resolution

I hope some of these suggestions help!  I'll keep working on optimizing the overlay, I know there's performance hiding in there still!

**Comment by geekbozu** [comment]
Works for me. It's now documented for others!
Keep up the fun work!
